pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "#check-success>=8"
    actions:
      merge:
        method: merge
      label:
        add: ["chore"]
