pull_request_rules:
  - name: Automatic merge Scala Steard
    conditions:
      - "author=scala-steward"
      - "#check-success>=8"
    actions:
      merge:
        method: merge
      label:
        add: ["chore"]
  - name: Automatic merge Dependabot
    conditions:
      - "author~=^dependabot"
      - "#check-success>=8"
    actions:
      merge:
        method: merge
      label:
        add: ["chore"]
