pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=scala-steward"
      - "status-success=CI"
      - "status-success=format"
    actions:
      merge:
        method: merge
      label:
        add: ["chore"]
