dist: xenial
language: scala

scala:
  - 2.12.11
  - 2.13.2

jdk:
  - openjdk11

env:
  matrix:
    - TRAVIS_NODE_VERSION="12.16.3" SCALAJS_VERSION="0.6.33"
    - TRAVIS_NODE_VERSION="12.16.3" SCALAJS_VERSION=""

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jobs:
  include:
    - name: "Node.10 Scala.js 0.6"
      env:  TRAVIS_NODE_VERSION="10.20.1" SCALAJS_VERSION="0.6.33"
      script: sbt ++$TRAVIS_SCALA_VERSION nodejs_v10/test
    - name: "Node.10 Scala.js 1.x"
      env:  TRAVIS_NODE_VERSION="10.20.1" SCALAJS_VERSION=""
      script: sbt ++$TRAVIS_SCALA_VERSION nodejs_v10/test

install:
  - rm -rf ~/.nvm &&
    git clone https://github.com/nvm-sh/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) &&
    source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.sbt/boot

