dist: xenial
language: scala

scala:
  - 2.12.11
  - 2.13.1

jdk:
  - openjdk11

env:
  global:
    - TRAVIS_NODE_VERSION="12.16.1" JOB_NAME="test"
  matrix:
    - SCALAJS_VERSION="0.6.32"
    - SCALAJS_VERSION="1.0.1"

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

matrix:
  include:
    - scala: 2.13.1
      env: TRAVIS_NODE_VERSION="10.19.0" JOB_NAME="test"
      script: sbt ++$TRAVIS_SCALA_VERSION nodejs_v10/test

install:
  - rm -rf ~/.nvm &&
    git clone https://github.com/nvm-sh/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) &&
    source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.sbt/boot

