dist: xenial
language: scala

scala:
  - 2.12.8
  - 2.13.0

env:
  - TRAVIS_NODE_VERSION="12.5.0"

jdk:
  - openjdk8
  - openjdk11

install:
  - rm -rf ~/.nvm &&
    git clone https://github.com/nvm-sh/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) &&
    source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheck test:scalafmtCheck clean current/doc core/doc coverage test
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]]; # Primary support is 2.12.x
    then
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    else echo "Skipping code coverage reporting on 2.13";
    fi

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

