name: CI
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Check Scalafmt/Scaladoc
        run: sbt ++2.13.2 scalafmtSbtCheck scalafmtCheck test:scalafmtCheck current/doc core/doc
      - name: Check README
        run: npm run lint-md
